32 Парсинг сообщений у бота
moevm/mse1h2024-telegram pull request #105
Opened 2024-04-08 17:41 UTC by Ajems

Пример отправки уведомления для подтверждения с бэенда
```
task = TaskTelegramMessage(chat_id="560639281",
                           params={"type": "confirm", 
                                   "table_name": "MSE",
                                   "table_url": "https://www.youtube.com/"})
await QueueManager().add_task_to_queue(task)
```
Так же, если в сценарии нужен другой текст сообщения, его можно добавить в качестве аргумента content 
```
TaskTelegramMessage(... content="Custom message" ...)
```

На данный момент сценарии использования ограничиваются подтверждением уведомления.

2024-04-09 07:10 UTC, ImSOLty requested changes

2024-04-09 07:10 UTC, ImSOLty commented on telegram_bot/bot/main.py
> +        if task["params"] and task["params"]["type"] == "confirm":
Не получается получить сообщение в боте, потому что на данный момент структура таска другая. При попытке установить в параметрах какие-нибудь значения, например:
```
task['params'] = {
            'type': 'confirm',
            'table_name': 'sheeesh',
            'table_url': 'https://docs.google.com/spreadsheets/d/1X9dFfHsfqOnGaFIOL7-gcKDDvDIbFPggSx07fjnaxPY'
        }
```
бот падает с исключением
```
 ERROR:asyncio:Task exception was never retrieved
mse-telegram-bot       | future: <Task finished name='Task-126' coro=<consumer() done, defined at /usr/local/lib/python3.10/site-packages/aio_pika/queue.py:31> exception=BadRequest('Can't parse entities: character '.' is reserved an
d must be escaped with the preceding '\'')>
mse-telegram-bot       | Traceback (most recent call last):
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/aio_pika/queue.py", line 37, in consumer
mse-telegram-bot       |     return await create_task(callback, message)
mse-telegram-bot       |   File "/tg_bot/bot/main.py", line 78, in process_task
mse-telegram-bot       |     await ButtonMessage(
mse-telegram-bot       |   File "/tg_bot/bot/messages/messages_types.py", line 84, in send
mse-telegram-bot       |     await sender_bot.send_message(
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 541, in decorator
mse-telegram-bot       |     result = await func(self, *args, **kwargs)
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 1015, in send_message
mse-telegram-bot       |     return await self._send_message(
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 735, in _send_message
mse-telegram-bot       |     result = await self._post(
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 629, in _post
mse-telegram-bot       |     return await self._do_post(
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 657, in _do_post
mse-telegram-bot       |     return await request.post(
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 200, in post
mse-telegram-bot       |     result = await self._request_wrapper(
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 379, in _request_wrapper
mse-telegram-bot       |     raise BadRequest(message)
mse-telegram-bot       | telegram.error.BadRequest: Can't parse entities: character '.' is reserved and must be escaped with the preceding '\'
```

2024-04-09 07:10 UTC, ImSOLty commented on telegram_bot/bot/main.py
> +        if task["params"] and task["params"]["type"] == "confirm":
UPD: пропустил комментарий к PR, сообщения в боте корректно приходят, однако непонятна причина исключения. Посмотри, пожалуйста.

2024-04-09 13:23 UTC, Ajems commented on telegram_bot/bot/main.py
>  async def stop(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
Не понял в чем ошибка ? Что конкретно стоит исправить/добавить ?

2024-04-09 13:26 UTC, ImSOLty commented on telegram_bot/bot/main.py
>  async def stop(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
Две stop функции

2024-04-09 14:10 UTC, Ajems commented on telegram_bot/bot/main.py
>  async def stop(update: Update, context: ContextTypes.DEFAULT_TYPE) -> None:
Моя ошибка при разрешении конфликтов

2024-04-09 14:22 UTC, Ajems commented on telegram_bot/bot/main.py
> +        if task["params"] and task["params"]["type"] == "confirm":
При отправке боту следующего запроса
```
task = TaskTelegramMessage(chat_id="560639281",
                                    params={"type": "confirm",
                                        "table_name": "sheeeesh",
                                        "table_url": "https://docs.google.com/spreadsheets/d/1X9dFfHsfqOnGaFIOL7-gcKDDvDIbFPggSx07fjnaxPY"})
```
ошибок на на бэке ни у бота нет. 

Однако я сталкивался с подобными ошибками во время выполнения таски. Проблема заключалась в символах, которые бот пишет пользователям. Все "необычные символы": например ! и . нужно экранировать, чтобы при форматировании markdown все корректно отображалось (это приколы api самого телеграмма). В классе TextContent это можно наблюдать. Если ты его не менял, то нужно будет разобраться на общем созвоне или 1:1.

2024-04-09 15:36 UTC, ImSOLty commented on telegram_bot/bot/main.py
> +        if task["params"] and task["params"]["type"] == "confirm":
Да, вероятнее всего ошибка была именно из-за того, что я пытался в лоб поменять task["params"]

2024-04-09 15:41 UTC, ImSOLty approved these changes
Разреши конфликты

2024-04-10 05:08 UTC, ImSOLty approved these changes

2024-04-10 05:08 UTC, merged