97 compare handler
moevm/mse1h2024-telegram pull request #128
Opened 2024-04-15 20:11 UTC by Ajems

Тестирование:
1. Создана [таблица ](https://docs.google.com/spreadsheets/d/1T0lRxKOBPaoIN00aGfYdEA26vpxXooSCfpvOlzXGVfA/edit#gid=0)
2. Команда /start в боте
3. Начать отслеживать
```
{
  "name": "Untitled spreadsheet",
  "table_id": "1T0lRxKOBPaoIN00aGfYdEA26vpxXooSCfpvOlzXGVfA",
  "provider": "GOOGLE",
  "update_frequency": 10,
  "pages": [
    {
      "id": "0",
      "name": "Sheet1",
      "teacher_column": "A",
      "columns": [
        "B", "C"
      ],
      "rule": ">",
      "notification_text": "string"
    }
  ]
}
```
4. Изменение данных таблицы
5. Получение уведомления
![image](https://github.com/moevm/mse1h2024-telegram/assets/70469206/7b2808ef-bc12-4e43-a10e-ba3c0d56fa7c)

2024-04-16 06:41 UTC, ImSOLty requested changes
Не получается протестировать работоспособность:
1. /start в бот
2. Создал копию предложенной таблицы
3. Начал отслеживание таблицы в приложении:
```
[
  {
    "_id": "5eb7cf5a86d9755df3a6c593",
    "name": "tmp",
    "table_id": "1dptlLvsbbzEXq_wAvzCfH17IAXvnvB19JZbG_uH7198",
    "provider": "GOOGLE",
    "update_frequency": 10,
    "pages": [
      {
        "id": "fde63b91-7dc6-437d-9570-4f6d1d4d3e2d",
        "name": "Лист1",
        "teacher_column": "A",
        "columns": [
          "B",
          "D"
        ],
        "rule": ">=",
        "notification_text": "hello world"
      }
    ]
  }
]
```
4. Внес следующие изменения в таблицу:
![image](https://github.com/moevm/mse1h2024-telegram/assets/48078801/953de2ff-8917-4098-8c55-cf428c73a978)

Информации от бота не поступает.

---

Также обрати внимание, структура моделей в приложении изменена. Перед отправкой PR необходимо пуллить изменения в ветку, после чего проверять работоспособность и отправлять на проверку.

2024-04-16 20:43 UTC, Ajems commented
"_id" в 3 пункте указывать не нужно, оно устанавливается автоматически
git pull делаю всегда перед пул реквестом, другое дело что он работает не так, как ожидается)) 
работоспособность проверена не только мной, но и еще двумя коллегами (всем трем людям приходили уведомления)

Попробуй не указывать "_id", если и так не будет работать буду фиксить

2024-04-18 19:49 UTC, Ajems commented
Проблема заключалась в отсутствии конвертации данных к ожидаемому типу (у меня работало, потому что "15" > "1", кажется, пора писать тесты 🙃). Сейчас поддерживается сравнение чисел и строк (встроенный - лексикографически).

2024-04-19 10:45 UTC, ImSOLty commented
Нет, я проверял и лексикографически, тут была прост моя глупая ошибка: не открыл доступ к таблице. My bad, спасибо, что заодно поправил проблему с типами <3

2024-04-19 10:45 UTC, ImSOLty approved these changes

2024-04-19 10:45 UTC, merged