143 Запротектить Endpoint'ы на бэкенде
moevm/mse1h2024-telegram pull request #146
Opened 2024-04-23 10:56 UTC by homin12

2024-04-23 15:39 UTC, ImSOLty requested changes
Почему POST /users оказался обделен? ( ´•︵•` )

2024-04-23 15:46 UTC, 1that commented
> @KirillSamokhin и @1that надо будет поправить запросы к беку на фронте, вам создать таску или сами создадите?

ок создам, чуть позже

2024-04-23 16:00 UTC, homin12 commented
> Почему POST /users оказался обделен? ( ´•︵•` )

вообще я так сделал потому что мне так сказал Дима, но я подозреваю, что это из-за того, что на эти endpoints отправляются запросы с бота и если оставить параметр admin то будет выдавать ошибку 401. 
И кстати я забыл убрать этот параметр у delete запроса (x_x)

2024-04-23 16:15 UTC, ImSOLty commented
Энивей после мерджа в main все поломается, поэтому предлагаю в рамках этого PR поправить запросы на фронте. Заодно +бейджик на github, хыхых

2024-04-24 08:34 UTC, ImSOLty approved these changes

2024-05-19 13:09 UTC, 1that commented
Теперь при ошибке связанной с токеном перекидывает на странницу логина

2024-05-20 14:36 UTC, ImSOLty approved these changes

2024-05-20 14:36 UTC, merged