102 валидация вводимых значений
moevm/mse1h2024-telegram pull request #151
Opened 2024-04-23 20:16 UTC by 1that

Написал валидацию для вводимых значений с помощью [vuelidate](https://vuelidate-next.netlify.app/).
Прошу проверить ввод разных значений на ошибки `(*>﹏<*)′

2024-04-24 05:23 UTC, ImSOLty requested changes
В общем и целом, кайф, спасибо. Комментарии:
1. В списке псевдонимов оказываются невалидными значения, содержащие знаки препинания и пробельные символы `,\/. -+()` и т. д. 
Пример использования: `Иванов И.И. | @ultra-killer1337 | Я(Иванов)`

2. Валидация столбцов. Использую кириллицу - возмущается на то, что буква не заглавная.
Пример: А (DEC: 192) или В (DEC: 194).
(+опционально можно ограничить длину до, скажем, 3 символов, вряд ли таблицы больше будут использоваться)

3. Хотим триммить все вводимые значения, включая:
* Название страницы
* Столбец преподавателей
* Столбец 1
* Столбец 2
* Название таблицы в системе
* ID таблицы
* Частота обновления в секундах

(Вполне возможно, что в большинстве случаев они отбриваются регулярками, я не проверял все случаи, но надо убедиться)
Пример: При установке поля "Название страницы" в `      Общий список        ` - страница не будет найдена.

2024-04-24 10:37 UTC, 1that commented
@ImSOLty можешь написать примеры какие псевдонимы считаются неправильно введенными?

2024-04-24 11:29 UTC, ImSOLty commented
> @ImSOLty можешь написать примеры какие псевдонимы считаются неправильно введенными?

Думаю, что мы считаем любые непустые псевдонимы корректными и просто обрезаем им пробелы по краям

2024-04-25 13:36 UTC, 1that commented
При вводе списка псевдонимов происходит валидация, что хотя бы первый псевдоним должен быть:
```abc |  |  | ```     такая строка пройдёт валидацию
```  |  |  |   ```        такая строка не пройдёт валидацию

2024-04-25 16:48 UTC, ImSOLty requested changes
> Использую кириллицу - возмущается на то, что буква не заглавная.
Пример: А (DEC: 192) или В (DEC: 194).

Извиняюсь, некорректно сформулировал. Речь была о том, что фидбек странный на кириллицу (ее тоже надо фильтровать). Если не сложно - поменяй, пожалуйста, фидбек, если сложно и долго - просто убери кириллицу из регулярки

2024-04-25 17:56 UTC, ImSOLty approved these changes

2024-04-25 17:56 UTC, merged