17 issue add Text kit, Button kit, example confirm notification
moevm/mse1h2024-telegram pull request #28
Opened 2024-03-11 20:55 UTC by Ajems

Созданы классы для удобного добавления и использования текстов и кнопок. 
Добавлен пример команды, для будущего использования для подтверждения получения уведомлений.

2024-03-12 17:14 UTC, ImSOLty requested changes

2024-03-12 17:14 UTC, ImSOLty commented on telegram_bot/bot/Messages/Messages.py
> +            raise Exception("Cannot use two panels of button at the same time")
Просьба придерживаться одного языка сообщений. "Вы получили это сообщение, так как вас упомянули в таблице" | "Cannot use two panels of button at the same time"

Заодно кажется, что тут хочется видеть не built-in исключение, а кастомное. Также по-хорошему бы добавить контроль этого случая при использовании.

2024-03-12 17:14 UTC, ImSOLty commented on telegram_bot/bot/main.py
> +        keyboard_button=[[Button.Start()], [Button.Help()], [Button.ConfirmCommand()]]
Возможно есть способ уменьшить в размерах keyboard кнопки для /help?
![image](https://github.com/moevm/mse1h2024-telegram/assets/48078801/13533e05-99df-4959-9ce8-cc1f0c8f9cdb)

2024-03-12 17:14 UTC, ImSOLty commented on telegram_bot/bot/main.py
> +from telegram_bot.bot.Messages.MessageContent.Button import *
1. Преобразуй скрипты внутри Messages в один пакет
2. В main импортируй их не от корня проекта
3. Постарайся не использовать import star. Плохая практика.
Что-то вроде:

```
from messages.messages_types import ButtonMessage
from messages.text_content import FormatText, Text
from messages.button import Button
```
К слову, пакеты и модули в питоне придерживаются lowercase (допускается snake_case для читаемости)

2024-03-12 17:14 UTC, ImSOLty commented on telegram_bot/bot/main.py
> +async def confirm_notification(update: Update, context: ContextTypes.DEFAULT_TYPE, table_name: str = "Примеры таблиц", table_url: str = "https://docs.google.com/spreadsheets/d/1xM3ntz2wm62ESlbkFD_07C
Имхо лучше временно вынести эти магические значения в переменные если их использование необходимо

2024-03-12 17:15 UTC, ImSOLty commented
Посмотри, пожалуйста, еще следующий момент:

Таймаут возникает при выполнении следующих действий:
1. Запуск приложения через docker compose up --build
2. Выполнение команды /confirm внутри бота
3. Нажатие на inline подтверждение

```
mse-telegram-bot       | No error handlers are registered, logging exception.
mse-telegram-bot       | Traceback (most recent call last):
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
mse-telegram-bot       |     yield
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 373, in handle_async_request
mse-telegram-bot       |     resp = await self._pool.handle_async_request(req)
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 216, in handle_async_request
mse-telegram-bot       |     raise exc from None
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection_pool.py", line 196, in handle_async_request
mse-telegram-bot       |     response = await connection.handle_async_request(
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/connection.py", line 101, in handle_async_request
mse-telegram-bot       |     return await self._connection.handle_async_request(request)
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 143, in handle_async_request
mse-telegram-bot       |     raise exc
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 113, in handle_async_request
mse-telegram-bot       |     ) = await self._receive_response_headers(**kwargs)
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 186, in _receive_response_headers
mse-telegram-bot       |     event = await self._receive_event(timeout=timeout)
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/httpcore/_async/http11.py", line 224, in _receive_event
mse-telegram-bot       |     data = await self._network_stream.read(
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/httpcore/_backends/anyio.py", line 31, in read
mse-telegram-bot       |     with map_exceptions(exc_map):
mse-telegram-bot       |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
mse-telegram-bot       |     self.gen.throw(typ, value, traceback)
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
mse-telegram-bot       |     raise to_exc(exc) from exc
mse-telegram-bot       | httpcore.ReadTimeout
mse-telegram-bot       | 
mse-telegram-bot       | The above exception was the direct cause of the following exception:
mse-telegram-bot       | 
mse-telegram-bot       | Traceback (most recent call last):
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/telegram/request/_httpxrequest.py", line 276, in do_request
mse-telegram-bot       |     res = await self._client.request(
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1574, in request
mse-telegram-bot       |     return await self.send(request, auth=auth, follow_redirects=follow_redirects)
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1661, in send
mse-telegram-bot       |     response = await self._send_handling_auth(
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1689, in _send_handling_auth
mse-telegram-bot       |     response = await self._send_handling_redirects(
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1726, in _send_handling_redirects
mse-telegram-bot       |     response = await self._send_single_request(request)
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/httpx/_client.py", line 1763, in _send_single_request
mse-telegram-bot       |     response = await transport.handle_async_request(request)
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 372, in handle_async_request
mse-telegram-bot       |     with map_httpcore_exceptions():
mse-telegram-bot       |   File "/usr/local/lib/python3.10/contextlib.py", line 153, in __exit__
mse-telegram-bot       |     self.gen.throw(typ, value, traceback)
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/httpx/_transports/default.py", line 86, in map_httpcore_exceptions
mse-telegram-bot       |     raise mapped_exc(message) from exc
mse-telegram-bot       | httpx.ReadTimeout
mse-telegram-bot       | 
mse-telegram-bot       | The above exception was the direct cause of the following exception:
mse-telegram-bot       | 
mse-telegram-bot       | Traceback (most recent call last):
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_application.py", line 1264, in process_update
mse-telegram-bot       |     await coroutine
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_handlers/basehandler.py", line 157, in handle_update
mse-telegram-bot       |     return await self.callback(update, context)
mse-telegram-bot       |   File "/tg_bot/bot/main.py", line 18, in start
mse-telegram-bot       |     await update.message.reply_html(rf"Hi, {user.mention_html()}!", reply_markup=ForceReply(selective=True))
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/telegram/_message.py", line 1801, in reply_html
mse-telegram-bot       |     return await self.get_bot().send_message(
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 2820, in send_message
mse-telegram-bot       |     return await super().send_message(
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 541, in decorator
mse-telegram-bot       |     result = await func(self, *args, **kwargs)
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 1015, in send_message
mse-telegram-bot       |     return await self._send_message(
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 581, in _send_message
mse-telegram-bot       |     result = await super()._send_message(
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 735, in _send_message
mse-telegram-bot       |     result = await self._post(
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 629, in _post
mse-telegram-bot       |     return await self._do_post(
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/telegram/ext/_extbot.py", line 347, in _do_post
mse-telegram-bot       |     return await super()._do_post(
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/telegram/_bot.py", line 657, in _do_post
mse-telegram-bot       |     return await request.post(
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 200, in post
mse-telegram-bot       |     result = await self._request_wrapper(
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 340, in _request_wrapper
mse-telegram-bot       |     raise exc
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/telegram/request/_baserequest.py", line 330, in _request_wrapper
mse-telegram-bot       |     code, payload = await self.do_request(
mse-telegram-bot       |   File "/usr/local/lib/python3.10/site-packages/telegram/request/_httpxrequest.py", line 293, in do_request
mse-telegram-bot     [...]

2024-03-12 19:06 UTC, Ajems commented on telegram_bot/bot/Messages/Messages.py
> +            raise Exception("Cannot use two panels of button at the same time")
1. Язык сообщений бота принят за русский. Ошибки работы программы на английском.
2. Думаю, стоит выделить в отдельную таску.

2024-03-12 19:06 UTC, Ajems commented on telegram_bot/bot/main.py
> +        keyboard_button=[[Button.Start()], [Button.Help()], [Button.ConfirmCommand()]]
Соединил /start и /help в один ряд.
Сообщение с подтверждением привел к виду соответствующий макету (кнопки подтвердить и таблица располагаются в одном ряду)

2024-03-12 19:06 UTC, Ajems commented on telegram_bot/bot/main.py
> +async def confirm_notification(update: Update, context: ContextTypes.DEFAULT_TYPE, table_name: str = "Примеры таблиц", table_url: str = "https://docs.google.com/spreadsheets/d/1xM3ntz2wm62ESlbkFD_07C
Это пример сообщения с подтверждением уведомления. Дефолтные значения установлены, чтобы функцию можно было передать в command_handler. Когда данные будут приходить от бэкенда, дефолтные значения можно убрать.

2024-03-13 07:29 UTC, ImSOLty approved these changes

2024-03-13 07:29 UTC, merged