29 Создание моделей (backend)
moevm/mse1h2024-telegram pull request #36
Opened 2024-03-16 15:22 UTC by homin12

2024-03-16 22:48 UTC, homin12 commented
Я так понял мне было бы не очень удобно работать над 30 задачей создавая отдельную ветку из мейна, так как для неё нужны модели из 29 задачи, то есть, получается, надо либо ждать мёржа 29 задачи либо начинать новую ветку от ветки 29 (｡>﹏<) . Или можно было бы сделать как нибудь по умному? ૮₍ ˶ᵔ ᵕ ᵔ˶ ₎ა

2024-03-17 10:57 UTC, ImSOLty requested changes
Дополнительно хочу попросить автоформатировать код при работе с ним для удобства ≽^•⩊•^≼

2024-03-17 10:57 UTC, ImSOLty commented on backend/app/main.py
> +    await init_db("mongodb://localhost:27017/bot_db", "bot_db")
Лучше задать в переменных окружения создать переменную названия бд (например bot_db), установить в docker compose имя хоста для монго (например mongo). После чего можно не "магически" писать uri, а в виде форматированной строки, использующей переменные окружения, что-то вроде:
```
user, passwd, db_name = os.getenv('MONGO_USER'), os.getenv('MONGO_PASS'), os.getenv('MONGO_DB')
await init_db(f"mongodb://{user}:{passwd}@mongodb/{db_name}?authSource=admin", db_name)
```

2024-03-17 10:57 UTC, ImSOLty commented on backend/app/routers/crud.py
> +from models.models import Teacher, Role, Level, Log, Table, Page, Provider
Проверь, пожалуйста, корректность импортов здесь и в других файлах.

2024-03-17 10:57 UTC, ImSOLty commented on backend/app/routers/crud.py
> +async def redact_rule(id: PydanticObjectId, name:str, new_name:str, t_col: str, columns: List[str], rule:str, text: str):
PUT /table/{table_id}/{page_name}/redact -> PUT /table/{table_id}/{page_id}
redact_rule -> edit_rule

Аналогично для других UPDATE-операций

2024-03-17 10:57 UTC, ImSOLty commented on backend/app/routers/crud.py
> +@router.delete("/tables/{table_id}/{page_name}", response_model=Table)
У страниц в таблицах есть id, думаю, лучше будет использовать их (page_name -> page_id)

2024-03-17 10:57 UTC, ImSOLty commented on backend/app/routers/crud.py
> +@router.get("/tables/", response_model=List[Table])
Missing GET /tables/{table_id}, response_model=Table

Аналогично для других READ-операций

2024-03-18 20:17 UTC, D1mitrii commented on backend/app/routers/crud.py
> +from models.models import Teacher, Role, Level, Log, Table, Page, Provider
При поднятии докер контейнера появляется данная ошибка
![image](https://github.com/moevm/mse1h2024-telegram/assets/90792387/a2776cfa-0f05-4941-910f-ab618b06a86f)

2024-03-18 20:33 UTC, D1mitrii commented on backend/app/routers/crud.py
> +@router.get("/tables/", response_model=List[Table])
Стоит убрать символ "/" в конце следующих endpoint'ов
![image](https://github.com/moevm/mse1h2024-telegram/assets/90792387/65327590-f6f5-43cc-a848-b7226742091f)

2024-03-19 14:41 UTC, ImSOLty requested changes

2024-03-19 14:41 UTC, ImSOLty commented on backend/requirements.txt
При создании контейнера бекенда зависимости подгружаются из requirements.txt, не стоит его очищать.

2024-03-20 08:13 UTC, ImSOLty approved these changes

2024-03-20 08:14 UTC, merged