31-18-fill-and-read-queue
moevm/mse1h2024-telegram pull request #45
Opened 2024-03-19 23:53 UTC by Ajems

2024-03-25 12:02 UTC, ImSOLty requested changes

2024-03-25 12:02 UTC, ImSOLty commented on telegram_bot/bot/queue_manager/queue_manager.py
> +class AnswerInterface(BaseModel): # need to use import but in crash :(
Причина, по которой в backend работают относительные импорты - uvicorn работает с пакетом, поэтому внутренние файлы знают относительные пути друг друга, в случае с telegram - у нас стартовой точкой в докерфайле является запуск скрипта через `python3 main.py`.

Если мы хотим пользоваться относительными импортами - нужно поправить стартовую точку на `python3 -m main.py` и изменить нынешние импорты в main.py

2024-03-25 12:41 UTC, ImSOLty commented
Closes #18

2024-03-25 12:48 UTC, Ajems commented on telegram_bot/Dockerfile
> +RUN pip install python-telegram-bot pydantic
нужен для создания класса AnswerInterface

2024-03-25 12:50 UTC, Ajems commented on backend/app/main.py
> +        task = TaskTelegramMessage(chat_id="560639281", content=f"hello {i}", params={"1": "1", "2": "2"})
Для показательного примера использования был взят мой id чата с ботом. Наверное, пример использования новых фич/кода нужно прилагать к комментарию PR, а не вставлять в код ?

2024-03-25 13:51 UTC, ImSOLty commented on telegram_bot/Dockerfile
> +RUN pip install python-telegram-bot pydantic
Да, я лишь про то, что команды 4-5 объединить

2024-03-25 15:00 UTC, Ajems commented on telegram_bot/bot/queue_manager/queue_manager.py
> +class AnswerInterface(BaseModel): # need to use import but in crash :(
исправил

2024-03-25 15:07 UTC, D1mitrii commented on backend/app/queue/queue_manager.py
> +                        host='rabbit')
Стоит использовать готовый `RABBIT_URI` из класса **Settings** для подключения

2024-03-25 17:25 UTC, Ajems commented on backend/app/queue/queue_manager.py
> +                        host='rabbit')
Спасибо. В будущем обязательно учту

2024-03-25 17:25 UTC, Ajems commented on backend/app/routers/add_sample_task.py
Исправил

2024-03-25 18:05 UTC, ImSOLty requested changes

2024-03-25 18:05 UTC, ImSOLty commented on backend/app/queue/queue_manager.py
> +                        host='rabbit')
Согласен с Димой, надо поправить

2024-03-25 18:05 UTC, ImSOLty commented on backend/app/config/settings.py
> +    # GDRIVE_API_CREDENTIALS: str
Эта переменная используется при обработке таблицы, в чем необходимость ее комментирования?

2024-03-25 18:05 UTC, ImSOLty commented on backend/app/main.py
> +# from .tables import tables_manager
Насколько мне известно, тут при импорте осуществляется пока что неприкрепленный функционал обработки таблиц

2024-03-25 18:05 UTC, ImSOLty commented on backend/app/main.py
> +        task = TaskTelegramMessage(chat_id="560639281", content=f"hello {i}", params={"1": "1", "2": "2"})
Все же необходимо вынести в переменную и не оставлять магических значений. Человеку, не видевшему этот код - непонятно, как исправить, почему у него контейнер падает :(

2024-03-25 18:10 UTC, Ajems commented on backend/app/config/settings.py
> +    # GDRIVE_API_CREDENTIALS: str
Потому что у меня нет кредов 😭😭😭
Дима сказал закомментировать чтобы работало

2024-03-25 18:10 UTC, Ajems commented on backend/app/main.py
> +# from .tables import tables_manager
Аналогичная ситуация

2024-03-26 07:38 UTC, ImSOLty approved these changes

2024-03-26 07:38 UTC, merged